/**
 * USER
 */
export const START_FETCHING_USER = 'START_FETCHING_USER';
export const RECEIVED_USER = 'RECEIVED_USER';
export const ERROR_FETCHING_USER = 'ERROR_FETCHING_USER';

/**
 * EDITOR
 */
export const START_FETCHING_UNASSIGNED_SUBMISSIONS =
  'START_FETCHING_UNASSIGNED_SUBMISSIONS';

export const RECEIVED_UNASSIGNED_SUBMISSIONS =
  'RECEIVED_UNASSIGNED_SUBMISSIONS';

export const ERROR_FETCHING_UNASSIGNED_SUBMISSIONS =
  'ERROR_FETCHING_UNASSIGNED_SUBMISSIONS';

/**
 * Transactions
 */
export const START_FETCHING_TXS = 'START_FETCHING_TXS';
export const RECEIVED_TXS = 'RECEIVED_TXS';
export const ERROR_FETCHING_TXS = 'ERROR_FETCHING_TXS';
export const ADDING_TX = 'ADDING_TX';
export const ADDED_TX = 'ADDED_TX';
export const ERROR_ADDING_TX = 'ERROR_ADDING_TX';

/**
 * OTHERS
 */
export const SET_NETWORK = 'SET_NETWORK';
export const SET_METAMASK = 'SET_METAMASK';

export const SETTING_ACCOUNTS = 'SETTING_ACCOUNTS';
export const ACCOUNTS_SET = 'ACCOUNTS_SET';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';
