/**
 * USER
 */
export const START_FETCHING_USER = 'START_FETCHING_USER';
export const RECEIVED_USER = 'RECEIVED_USER';
export const ERROR_FETCHING_USER = 'ERROR_FETCHING_USER';

/**
 * EDITOR
 */
export const START_FETCHING_UNASSIGNED_SUBMISSIONS =
  'START_FETCHING_UNASSIGNED_SUBMISSIONS';

export const RECEIVED_UNASSIGNED_SUBMISSIONS =
  'RECEIVED_UNASSIGNED_SUBMISSIONS';

export const ERROR_FETCHING_UNASSIGNED_SUBMISSIONS =
  'ERROR_FETCHING_UNASSIGNED_SUBMISSIONS';

/**
 * OTHERS
 */
export const SET_NETWORK = 'SET_NETWORK';

